config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, path: 'auth',
                   path_names: {
                      sign_in: 'login',
                      sign_out: 'logout',
                      edit: 'profile'
                   }

  authenticate :user do
    resources :announcements, only: [:new, :edit, :create, :update, :destroy]
    resources :reservations, only: [:new, :edit, :create, :update, :destroy]
  end

  resources :announcements, only: [:index, :show]

end

app/models/announcement.rb
class Announcement < ApplicationRecord
  belongs_to :user
  has_many :pictures, :inverse_of => :announcement, index_errors: true
  accepts_nested_attributes_for :pictures, :allow_destroy => true

  validates :game_title,
            :game_type,
            :game_min_players,
            :game_max_players,
            :game_min_age,
            :game_status,
            :game_min_duration,
            :game_max_duration,
            :title,
            :description,
            :availibity,
            :min_reservation,
            :max_reservation,
            :renting_price,
            :caution_price,
            :pictures,
            presence: true

  validates_length_of :game_title, :minimum => 3, :maximum => 30
  validates :game_type, numericality: { only_integer: true, greater_than: 0, less_than: 5 }
  validates :game_min_players, numericality: { only_integer: true, greater_than: 0, less_than: 1000 }
  validates :game_max_players, numericality: { only_integer: true, greater_than: :game_min_players, less_than: 1000 }
  validates :game_min_age, numericality: { only_integer: true, greater_than: 2, less_than: 19 }
  validates :game_status, numericality: { only_integer: true, greater_than: 0, less_than: 5 }
  validates :game_min_duration, numericality: { only_integer: true, greater_than: 0, less_than: 300 }
  validates :game_max_duration, numericality: { only_integer: true, greater_than: :game_min_duration, less_than: 600 }
  validates_length_of :title, :minimum => 3, :maximum => 30
  validates_length_of :description, :minimum => 10, :maximum => 5000
  validates_length_of :availibity, :minimum => 10, :maximum => 5000
  validates :min_reservation, numericality: { only_integer: true, greater_than: 0, less_than: 8 }
  validates :max_reservation, numericality: { only_integer: true, greater_than: :min_reservation, less_than: 366 }

  monetize :renting_price, :as =>"renting", :numericality => {
    :greater_than_or_equal_to => 1,
    :less_than_or_equal_to => 99999
  }

  monetize :caution_price, :as =>"caution", :numericality => {
    :greater_than_or_equal_to => 1,
    :less_than_or_equal_to => 99999
  }

  self.per_page = 20
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    announcements = Announcement.all
    if params[:category]
      announcements = announcements.where(["game_category = ?", params[:category]])
    end
    if params['sort']
      f = params['sort'].split(',').first
      field = f[0] == '-' ? f[1..-1] : f
      order = f[0] == '-' ? 'DESC' : 'ASC'
      if Announcement.new.has_attribute?(field)
        announcements = announcements.order("#{field} #{order}")
      end
    end
    announcements = Announcement.page(params[:page] ? params[:page][:number] : 1)
    render json: announcements, meta: pagination_meta(announcements),  include: ['user', 'pictures']
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
    @announcement.pictures.build
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.user = current_user
    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


    def pagination_meta(object)
      {
        current_page: object.current_page,
        next_page: object.next_page,
        prev_page: object.previous_page,
        total_pages: object.total_pages,
        total_count: object.total_entries
      }
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(
        :game_title,
        :game_type,
        :game_min_players,
        :game_max_players,
        :game_min_age,
        :game_status,
        :game_min_duration,
        :game_max_duration,
        :title,
        :description,
        :availibity,
        :min_reservation,
        :max_reservation,
        :renting,
        :caution,
        game_content: [],
        game_tags: [],
        pictures_attributes: [:image, :image_file_name]
      )
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_with(model: announcement, local: true) do |f| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>


  <div class="field">
    <%= f.label :min_reservation %><br />
    <%= f.number_field :min_reservation, in: 1...365 %>
  </div>

  <div class="field">
    <%= f.label :max_reservation %><br />
    <%= f.number_field :max_reservation, in: 1...365 %>
  </div>

  <div class="field">
    <%= f.label :renting %><br />
    <%= f.number_field :renting, in: 1...999999, step: 0.01 %>
  </div>

  <div class="field">
    <%= f.label :caution %><br />
    <%= f.number_field :caution, in: 1...999999, step: 0.01 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/details.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Partajouer</title>
    <%= javascript_pack_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,700" rel="stylesheet">
  </head>
  <body>
    <h1>Hello</h1>
  </body>
  </html>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Announcements</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_announcement_path %>

app/views/announcements/new.html.erb
<div class="edit__page--white">
  <%= react_component("CustomMenu", {
      isLoggedIn: user_signed_in?,
      user: current_user,
      links: {
        signup: url_for(new_user_registration_path),
        login: url_for(new_user_session_path),
        logout: url_for(destroy_user_session_path),
        editProfile: url_for(edit_user_registration_path),
      },
      profilePictureUrl: user_signed_in? ? current_user.avatar.url('thumb') : '',
    })
  %>
  <%= form_with(model: @announcement, local: true) do |f| %>
    <%= react_component("AnnouncementForm", {stepPic: [image_path("quel-jeu.png"), image_path("appareil-photo.png"), image_path("personnalize.png")]}) %>
  <% end %>
</div>